- name: create firewall rule
  hosts: localhost
  tasks:
          - name: allow http
            gcp_compute_firewall:
                    name: "allow-http"
                    allowed:
                    - ip_protocol: tcp
                      ports:
                        - '80'
                    priority: 1000
                    project: "{{ project_id }}"
                    state: present
                    auth_kind: serviceaccount
                    service_account_file: "{{ service_account_file }}"
                    source_ranges: 0.0.0.0/0

          - name: create a network
            gcp_compute_network:
                    name: 'network'
                    project: "{{ project_id }}"
                    auth_kind: serviceaccount
                    auto_create_subnetworks: yes
                    service_account_file: "{{ service_account_file }}"
                    state: present
                    scopes:
                         - https://www.googleapis.com/auth/compute
            register: network

          - name: create an address
            gcp_compute_address:
                    name: 'template-address'
                    region: europe-west1
                    project: "{{ project_id }}"
                    auth_kind: serviceaccount
                    service_account_file: "{{ service_account_file }}"  
                    state: present
            register: address

          - name: create a instance template
            google.cloud.gcp_compute_instance_template:
                     name: 'instance-template'
                     properties:
                            disks:
                                - auto_delete: 'true'
                                  boot: 'true'
                                  initialize_params:
                                        disk_type: pd-balanced
                                        source_image: "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-10-buster-v20211209"
                            machine_type: n1-standard-1
                            network_interfaces:
                                - network: "{{ network }}"
                                  access_configs:
                                        - name: test-config
                                          type: ONE_TO_ONE_NAT
                                          nat_ip: "{{ address }}"
                     project: "{{ project_id }}"
                     auth_kind: serviceaccount
                     zone: europe-west-1
                     service_account_file:  "{{ service_account_file }}"
                     state: present
            register: instancetemplate

          - name: create a instance group manager
            gcp_compute_instance_group_manager:
                     name: 'groupmanager'
                     base_instance_name: test1-child
                     instance_template: "{{ instancetemplate }}"
                     target_size: 3
                     zone: europe-west1-b
                     project: "{{ project_id }}"
                     auth_kind: serviceaccount
                     service_account_file: "{{ service_account_file }}"
                     state: present
