        - name: Install Python
          apt:
                  name: "{{ item }}"
                  state: present
          with_items:
                  - python3
                  - python3-setuptools
                  - python3-dev
                  - build-essential
                  - python3-pip
                  - python-mysqldb
                  - git  


        - name: Install Flask dependency
          pip:
                  name: "{{ item }}"
                  state: present
          with_items:
                  - flask
                  - flask-mysql
        
                    #   - name: Copy source code
                    #    copy: src=app.py dest=/opt/app.py
        
                    #  - name: Start web server
                    # shell: FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port 80 &


