        - name: install python flask dependency
          pip:
                  name: "{{ item }}"
                  state: present
          with_items:
                  - flask
                  - flask-mysql
        
        - name: git clone source code
          git:
                  repo: 'https://www.github.com/mmumshad/simple-webapp'
                  dest: /opt/simple-webapp

        - name: print command
          debug:
                  msg:  MYSQL_DATABASE_HOST={{ hostvars['db-server']['private_ip'] }} FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port=80 &

        - name: start web server
          shell: MYSQL_DATABASE_HOST={{ hostvars['db-server']['private_ip'] }} FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port=80 &
